version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: docutils
    versions:
    - "0.16"
    - "0.17"
  - dependency-name: pyflakes
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
